services:
  postgres:
    image: postgres:16
    container_name: task-api-db
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: '39421s'       # mot de passe vide
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-api-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: task-api-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@taskapi.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8088:80"
    networks:
      - task-api-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  task-api-network:
    driver: bridge
