version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: ticket-api-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticketdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticket-api-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: ticket-api-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ticketapi.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - ticket-api-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  ticket-api-network:
    driver: bridge